export const AuthActionTypes = {
    REGISTER_SUCCESS: "REGISTER_SUCCESS",
    REGISTER_FAIL: "REGISTER_FAIL",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
    LOGOUT: "LOGOUT",
    SET_MESSAGE: "SET_MESSAGE",
    CLEAR_MESSAGE: "CLEAR_MESSAGE",

}

export const TaskActionTypes = {
    GET_ALL_TASK: "GET_ALL_TASK",
    DELETE_TASK: "DELETE_TASK",
    ADD_TASK: "ADD_TASK"
}